[project]
name = "ece-bigdata-fall"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "t-dous-ece", email = "tao.dous@edu.ece.fr" }
]
requires-python = ">=3.13"
dependencies = [
    "faker>=40.39.0",
]

[project.scripts]
dataset-users = "ece_bigdata_fall.dataset_users:main"
dataset-orders = "ece_bigdata_fall.dataset_orders:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
